---
title: "R Notebook"
output: html_notebook
---
```{r}
#install.packages("RSQLite")
library(RSQLite)
```
```{r}
con <- dbConnect(RSQLite::SQLite(), "MedArticle.db")
dbListTables(con)
```

```{r}
# create Table History
dbExecute(con, "DROP TABLE if EXISTS History;")
dbExecute(con, "CREATE TABLE History (History_ID INTEGER PRIMARY KEY,  PubStatus TEXT, Year INTEGER, Month INTEGER, Day INTEGER, Hour INTEGER, Minute INTEGER, Second INTEGER);")
dbListTables(con)
```

```{r}
# create Table Journal
dbExecute(con, "DROP TABLE if EXISTS Journal;")
dbExecute(con, "CREATE TABLE Journal (Journal_ID INTEGER PRIMARY KEY,  Journal_ISSN TEXT, IssnType TEXT, CitedMedium TEXT, Volume INTEGER, Issue INTEGER, PubDate DATE, Title TEXT, ISOAbbreviation TEXT);")
dbListTables(con)
```

```{r}
# create Table Author
dbExecute(con, "DROP TABLE if EXISTS Author;")
dbExecute(con, "CREATE TABLE Author (Author_ID INTEGER PRIMARY KEY,  LastName TEXT, ForeName TEXT, Initials TEXT, Affiliation TEXT, ValidYN BOOLEAN);")
dbListTables(con)
```

```{r}
# create Table AuthorList
dbExecute(con, "DROP TABLE if EXISTS AuthorList;")
dbExecute(con, "CREATE TABLE AuthorList (AuthorList_ID INTEGER PRIMARY KEY, CompleteYN boolean, Author_ID INTEGER, FOREIGN KEY (Author_ID) REFERENCES Author(Author_ID));")
dbListTables(con)
```

```{r}
# create Table Article
dbExecute(con, "DROP TABLE if EXISTS Article;")
dbExecute(con, "CREATE TABLE Article (Article_ID INTEGER PRIMARY KEY,  PubModel TEXT, ArticleTitle TEXT, MedlinePgn TEXT, Language TEXT, Journal_ID INTEGER, AuthorList_ID INTEGER, FOREIGN KEY (Journal_ID) REFERENCES Journal(Journal_ID), FOREIGN KEY (AuthorList_ID) REFERENCES AuthorList(AuthorList_ID));")
dbListTables(con)
```

```{r}
# create Table ArticleHasHistory
dbExecute(con, "DROP TABLE if EXISTS ArticleHasHistory;")
dbExecute(con, "CREATE TABLE ArticleHasHistory (History_ID INTEGER, Article_ID INTEGER, PRIMARY KEY (History_ID, Article_ID), FOREIGN KEY (History_ID) REFERENCES History(History_ID), FOREIGN KEY (Article_ID) REFERENCES Article(Article_ID) );")
dbListTables(con)
```


```{r}
#install.packages("tidyr")
#install.packages("purrr")
#install.packages("xml2")
#library(tidyr)
#library(purrr)
#library(xml2)

#install.packages("magrittr") # package installations are only needed the first time you use it
#install.packages("dplyr")    # alternative installation of the %>%
#library(magrittr) # needs to be run every time you start R and want to use %>%
#library(dplyr)    # alternatively, this also loads %>%
```
```{r}
#library(XML)
```

```{r}
#doc<-xmlParse("pubmed_sample.xml")
# xmldf <- xmlToDataFrame(nodes = getNodeSet(doc, "//PubmedArticleSet"))
# View(xmldf)
```

```{r}

```





```{r}
#products <- read_xml("pubmed_sample.xml") %>% xml_find_all("//PubmedArticleSet")
```


